language: perl

os:
    - linux
    - osx

sudo: false

fast_finish: true

install: "echo"
dist: xenial

jdk: openjdk11

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test

script:
    - perl Configure.pl $RAKUDO_OPTIONS --moar-option=--cc=$(command -v gcc-6 >/dev/null 2>&1; if [ $? -eq 1 ]; then printf "gcc"; else printf "gcc-6"; fi)
    - "make install"
    - (cd ~/build/rakudo/rakudo/ && prove -e ~/build/rakudo/rakudo/install/bin/perl6 -vlr t)

branches:
   only:
     - master
     - /smoke-me/

notifications:
  irc:
    channels:
      - "irc.freenode.net#raku-dev"
    on_success: change
    on_failure: always
    template:
      - "Rakudo build %{result}. %{author} '%{commit_message}'"
      - "%{build_url} %{compare_url}"

env:
    - RAKUDO_OPTIONS="--backends=moar --gen-nqp        --gen-moar"
    - RAKUDO_OPTIONS="--backends=moar --gen-nqp=master --gen-moar"
    - RAKUDO_OPTIONS="--backends=moar --gen-nqp=master --gen-moar=master"
    - RAKUDO_OPTIONS="--backends=jvm  --gen-nqp"
    - RAKUDO_OPTIONS="--backends=jvm  --gen-nqp=master"

matrix:
  allow_failures:
    - env: RAKUDO_OPTIONS="--backends=jvm  --gen-nqp"
    - env: RAKUDO_OPTIONS="--backends=jvm  --gen-nqp=master"
